package main

import (
	"fmt"
	"os"
	"strings"
	"sync"
)

// RunOpts is the union of options used by the kloop primitives.
type RunOpts struct {
	Question      string
	Rounds        int
	Model         string
	ModelExplicit bool   // true if user passed --model
	MaxTokens     int
	Executor      string // "auto" | "claude" | "api"
	DryRun        bool
	Close         bool // loop only — append a final turn returning to mind[0]
}

// Loop runs a kloop: minds respond in sequence, each seeing only the prior
// response. With Close=true, the chain ends with a final turn by mind[0],
// who is now reflecting on responses generated by its own original answer.
// That returning step is the strange loop: the system sees what its own
// thinking caused, then thinks about that.
func Loop(minds []*Mind, opts RunOpts) error {
	if len(minds) < 1 {
		return fmt.Errorf("loop needs at least one mind")
	}
	if opts.Rounds < 1 {
		opts.Rounds = 1
	}

	chain := []*Mind{}
	for r := 0; r < opts.Rounds; r++ {
		chain = append(chain, minds...)
	}
	if opts.Close && len(minds) >= 2 {
		chain = append(chain, minds[0])
	}

	var executor Executor
	if !opts.DryRun {
		var err error
		executor, err = NewExecutor(opts.Executor, opts.Model, opts.MaxTokens, opts.ModelExplicit)
		if err != nil {
			return err
		}
		defer executor.PrintUsage()
		fmt.Fprintf(os.Stderr, "[executor: %s]\n", executor.Name())
	}

	prior := opts.Question
	priorAuthor := "User"

	for i, m := range chain {
		isFirst := i == 0
		isReturn := opts.Close && i == len(chain)-1 && len(minds) >= 2 && m == minds[0]

		userMsg := buildLoopUserMsg(opts.Question, prior, priorAuthor, isFirst, isReturn)

		header := fmt.Sprintf("turn %d/%d — %s", i+1, len(chain), m.Name)
		if isReturn {
			header += "  [strange loop: returning to origin]"
		}
		printHeader(header)

		if opts.DryRun {
			printDryRun(m, userMsg)
			prior = fmt.Sprintf("(dry-run response from %s)", m.Name)
		} else {
			resp, err := executor.Call(m.SystemPrompt(), []apiMessage{
				{Role: "user", Content: userMsg},
			})
			if err != nil {
				return fmt.Errorf("turn %d (%s): %w", i+1, m.Name, err)
			}
			fmt.Println(resp)
			prior = resp
		}
		priorAuthor = m.Name
	}
	return nil
}

func buildLoopUserMsg(original, prior, priorAuthor string, isFirst, isReturn bool) string {
	if isFirst {
		return original
	}
	if isReturn {
		return fmt.Sprintf(`The original question was:

%s

Your initial response set off a chain of replies. The chain has now returned to you. The most recent response was from %s:

%s

You are seeing the consequences of your own thinking, refracted through other minds. Now respond — not to the original question again, but to the chain of thinking your answer triggered. Where did the loop go that surprised you? What does the system look like now that it has seen itself?`, original, priorAuthor, prior)
	}
	return fmt.Sprintf(`The original question was:

%s

%s just responded:

%s

Now respond from your identity. You may agree, disagree, build on, or reframe. Be yourself.`, original, priorAuthor, prior)
}

// Braid runs a single mind through N rounds of self-reflection.
// The mind's previous output becomes the substrate of its next pass.
// This is the cleanest strange loop: the system whose output is its own input.
func Braid(m *Mind, opts RunOpts) error {
	if opts.Rounds < 1 {
		opts.Rounds = 3
	}

	var executor Executor
	if !opts.DryRun {
		var err error
		executor, err = NewExecutor(opts.Executor, opts.Model, opts.MaxTokens, opts.ModelExplicit)
		if err != nil {
			return err
		}
		defer executor.PrintUsage()
		fmt.Fprintf(os.Stderr, "[executor: %s]\n", executor.Name())
	}

	history := []apiMessage{
		{Role: "user", Content: opts.Question},
	}

	for r := 0; r < opts.Rounds; r++ {
		printHeader(fmt.Sprintf("braid %d/%d — %s", r+1, opts.Rounds, m.Name))

		var resp string
		if opts.DryRun {
			fmt.Printf("[system: %d chars from %s]\n", len(m.SystemPrompt()), m.Slug)
			fmt.Printf("[history len=%d]\n", len(history))
			fmt.Printf("[user]: %s\n", history[len(history)-1].Content)
			resp = fmt.Sprintf("(dry-run response from %s, round %d)", m.Name, r+1)
		} else {
			out, err := executor.Call(m.SystemPrompt(), history)
			if err != nil {
				return fmt.Errorf("braid round %d: %w", r+1, err)
			}
			fmt.Println(out)
			resp = out
		}

		history = append(history, apiMessage{Role: "assistant", Content: resp})
		if r < opts.Rounds-1 {
			history = append(history, apiMessage{Role: "user", Content: braidPrompt(r + 2)})
		}
	}
	return nil
}

func braidPrompt(round int) string {
	switch round {
	case 2:
		return "Now reflect on what you just said. What did you miss? What would you tighten or rethink? Speak as yourself, critiquing yourself."
	case 3:
		return "Reflect again — but this time, watch the reflecting itself. Where is the strange loop in your own thinking here? What does the system look like when it sees itself looking?"
	default:
		return "Reflect again. Each pass should go deeper — into pattern, not detail."
	}
}

// Panel asks N minds the same question in parallel, then sends all responses
// to a synthesis mind that finds what unifies, what disagrees, and what
// nobody saw. Loop closes if the synthesis mind is also one of the panelists.
func Panel(minds []*Mind, synthesis *Mind, opts RunOpts) error {
	if len(minds) < 2 {
		return fmt.Errorf("panel needs at least 2 minds")
	}

	var executor Executor
	if !opts.DryRun {
		var err error
		executor, err = NewExecutor(opts.Executor, opts.Model, opts.MaxTokens, opts.ModelExplicit)
		if err != nil {
			return err
		}
		defer executor.PrintUsage()
		fmt.Fprintf(os.Stderr, "[executor: %s]\n", executor.Name())
	}

	type result struct {
		mind *Mind
		text string
		err  error
	}
	results := make([]result, len(minds))

	var wg sync.WaitGroup
	for i, m := range minds {
		wg.Add(1)
		go func(i int, m *Mind) {
			defer wg.Done()
			if opts.DryRun {
				results[i] = result{mind: m, text: fmt.Sprintf("(dry-run from %s)", m.Name)}
				return
			}
			resp, err := executor.Call(m.SystemPrompt(), []apiMessage{
				{Role: "user", Content: opts.Question},
			})
			results[i] = result{mind: m, text: resp, err: err}
		}(i, m)
	}
	wg.Wait()

	for _, r := range results {
		printHeader(r.mind.Name)
		if r.err != nil {
			fmt.Printf("[error: %v]\n", r.err)
			continue
		}
		if opts.DryRun {
			fmt.Printf("[system: %d chars from %s]\n", len(r.mind.SystemPrompt()), r.mind.Slug)
			fmt.Printf("[user]: %s\n", opts.Question)
		}
		fmt.Println(r.text)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Original question:\n\n%s\n\n", opts.Question))
	sb.WriteString("The panel responded:\n\n")
	for _, r := range results {
		if r.err != nil || r.text == "" {
			continue
		}
		sb.WriteString(fmt.Sprintf("=== %s ===\n%s\n\n", r.mind.Name, r.text))
	}
	sb.WriteString("Synthesize. Find what unifies, what disagrees, what nobody saw, and what the panel collectively missed.")

	printHeader(fmt.Sprintf("synthesis — %s", synthesis.Name))
	if opts.DryRun {
		fmt.Printf("[system: %d chars from %s]\n", len(synthesis.SystemPrompt()), synthesis.Slug)
		fmt.Printf("[user]: %s\n", truncate(sb.String(), 600))
		return nil
	}
	resp, err := executor.Call(synthesis.SystemPrompt(), []apiMessage{
		{Role: "user", Content: sb.String()},
	})
	if err != nil {
		return fmt.Errorf("synthesis: %w", err)
	}
	fmt.Println(resp)
	return nil
}

func printHeader(s string) {
	bar := strings.Repeat("━", 3)
	fmt.Printf("\n%s %s %s\n", bar, s, bar)
}

func printDryRun(m *Mind, userMsg string) {
	fmt.Printf("[system: %d chars from %s]\n", len(m.SystemPrompt()), m.Slug)
	fmt.Printf("[user]: %s\n", userMsg)
}
