// hofstadter — orchestrate the brilliant-minds collection with kloops.
//
// A "kloop" is a strange loop in which the output of one mind becomes the
// input of the next, optionally closing back to the first mind so it
// reflects on responses generated by its own initial answer.
//
// Three primitives:
//   loop   — chain N distinct minds; output snakes through them.
//   braid  — single mind self-reflects across rounds.
//   panel  — N minds answer in parallel, then a synthesis mind responds.
//
// All three accept --dry-run, which prints prompts without calling the API.
package main

import (
	"fmt"
	"io"
	"os"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
	case "list":
		cmdList(os.Args[2:])
	case "show":
		cmdShow(os.Args[2:])
	case "summon":
		cmdSummon(os.Args[2:])
	case "loop":
		cmdLoop(os.Args[2:])
	case "braid":
		cmdBraid(os.Args[2:])
	case "panel":
		cmdPanel(os.Args[2:])
	case "-h", "--help", "help":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", os.Args[1])
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `hofstadter — orchestrate brilliant minds with kloops

Commands:
  list                                list available minds
  show <id>                           print a mind's ACTIVATION.md
  summon <id>                         print full system prompt for a mind
  loop <id1> [id2 ...] [flags]        chain minds; each responds to the prior
  braid <id> [flags]                  single mind self-reflects across rounds
  panel <id1>,<id2>,... [flags]       minds answer in parallel, then synthesize

Flags (loop / braid / panel):
  --question "..."   the question (or pipe one on stdin)
  --rounds N         loop: traversals (default 1).  braid: reflections (default 3).
  --no-close         loop: do NOT close back to first mind (default closes if N>=2)
  --synthesis <id>   panel: synthesis mind (default: the_assembler)
  --executor KIND    auto (default) | claude | api
                       claude: shell out to local 'claude' binary
                       api:    HTTP to api.anthropic.com (needs key)
                       auto:   claude if on PATH, else api
  --model NAME       Claude model (default: claude-sonnet-4-6 for api;
                     claude executor uses your CLI default unless set)
  --max-tokens N     api executor: max output tokens per turn (default 1024)
  --dry-run          print prompts; do not call any executor

Environment:
  ANTHROPIC_API_KEY     required for --executor=api (auto falls back to it)
  BRILLIANT_MINDS_ROOT  override path to the repo (else auto-detected)

Mind ids may be either snake_case (douglas_hofstadter) or kebab-case
(douglas-hofstadter). Run "hofstadter list" to see all available minds.`)
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}

func dieMsg(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", a...)
	os.Exit(1)
}

// readStdin returns piped stdin content, or "" if stdin is a tty.
func readStdin() string {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return ""
	}
	if (fi.Mode() & os.ModeCharDevice) != 0 {
		return ""
	}
	b, err := io.ReadAll(os.Stdin)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}
