"""
Question Generation Engine

Enables restored brilliant minds to generate evaluation questions
based on their unique expertise and values.

This module provides:
- Question and QuestionSet data classes for structured question management
- QuestionGenerator for AI-powered question generation from a mind's perspective
- Project information helpers for context-aware generation
- Quality filtering and diversity assurance mechanisms
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Set, Tuple
from enum import Enum
from collections import defaultdict
import json
import re
import hashlib
import uuid
from pathlib import Path


class QuestionCategory(Enum):
    """Categories for classifying evaluation questions."""
    ARCHITECTURE = "architecture"
    CODE_QUALITY = "code_quality"
    DOCUMENTATION = "documentation"
    TESTING = "testing"
    SECURITY = "security"
    PERFORMANCE = "performance"
    MAINTAINABILITY = "maintainability"
    INNOVATION = "innovation"
    METHODOLOGY = "methodology"
    PHILOSOPHY = "philosophy"
    OTHER = "other"

    @classmethod
    def from_string(cls, value: str) -> 'QuestionCategory':
        """Convert string to QuestionCategory, with fuzzy matching."""
        value_lower = value.lower().strip()

        # Direct match
        for category in cls:
            if category.value == value_lower:
                return category

        # Fuzzy matching based on keywords
        category_keywords = {
            cls.ARCHITECTURE: ['architecture', 'design', 'structure', 'system', 'component', 'module', 'pattern', 'layer'],
            cls.CODE_QUALITY: ['code quality', 'clean code', 'readability', 'style', 'convention', 'smell', 'refactor'],
            cls.DOCUMENTATION: ['documentation', 'docs', 'comment', 'readme', 'api doc', 'docstring'],
            cls.TESTING: ['test', 'testing', 'coverage', 'unit test', 'integration', 'e2e', 'tdd', 'bdd'],
            cls.SECURITY: ['security', 'vulnerability', 'auth', 'encryption', 'injection', 'xss', 'csrf'],
            cls.PERFORMANCE: ['performance', 'speed', 'latency', 'throughput', 'optimization', 'cache', 'memory', 'cpu'],
            cls.MAINTAINABILITY: ['maintainability', 'maintenance', 'technical debt', 'complexity', 'coupling', 'cohesion'],
            cls.INNOVATION: ['innovation', 'creative', 'novel', 'breakthrough', 'cutting-edge', 'state-of-the-art'],
            cls.METHODOLOGY: ['methodology', 'process', 'workflow', 'agile', 'practice', 'approach', 'strategy'],
            cls.PHILOSOPHY: ['philosophy', 'principle', 'belief', 'value', 'ethic', 'vision', 'mission'],
        }

        for category, keywords in category_keywords.items():
            for keyword in keywords:
                if keyword in value_lower:
                    return category

        return cls.OTHER


@dataclass
class Question:
    """
    Represents a single evaluation question generated by a brilliant mind.

    Attributes:
        id: Unique identifier for the question
        text: The actual question text
        category: Classification of the question type
        rationale: Why this question matters to this mind
        good_answer_indicators: Signs of a good answer
        bad_answer_indicators: Signs of a poor answer
        difficulty: Question difficulty level (1-5)
        weight: Importance weight for this mind (0.0-1.0)
        generated_by: Name of the mind that generated this question
    """
    id: str
    text: str
    category: QuestionCategory
    rationale: str
    good_answer_indicators: List[str]
    bad_answer_indicators: List[str]
    difficulty: int
    weight: float
    generated_by: str

    def __post_init__(self):
        """Validate question data after initialization."""
        if not 1 <= self.difficulty <= 5:
            raise ValueError(f"Difficulty must be between 1 and 5, got {self.difficulty}")
        if not 0.0 <= self.weight <= 1.0:
            raise ValueError(f"Weight must be between 0.0 and 1.0, got {self.weight}")
        if not self.text.strip():
            raise ValueError("Question text cannot be empty")
        if not self.id:
            self.id = self._generate_id()

    def _generate_id(self) -> str:
        """Generate a unique ID based on question content."""
        content = f"{self.text}:{self.generated_by}"
        return hashlib.sha256(content.encode()).hexdigest()[:12]

    def to_dict(self) -> Dict[str, Any]:
        """Convert question to dictionary representation."""
        return {
            "id": self.id,
            "text": self.text,
            "category": self.category.value,
            "rationale": self.rationale,
            "good_answer_indicators": self.good_answer_indicators,
            "bad_answer_indicators": self.bad_answer_indicators,
            "difficulty": self.difficulty,
            "weight": self.weight,
            "generated_by": self.generated_by
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Question':
        """Create a Question from dictionary representation."""
        return cls(
            id=data.get("id", ""),
            text=data["text"],
            category=QuestionCategory.from_string(data["category"]) if isinstance(data["category"], str) else data["category"],
            rationale=data["rationale"],
            good_answer_indicators=data.get("good_answer_indicators", []),
            bad_answer_indicators=data.get("bad_answer_indicators", []),
            difficulty=data.get("difficulty", 3),
            weight=data.get("weight", 0.5),
            generated_by=data["generated_by"]
        )

    def similarity_hash(self) -> str:
        """Generate a hash for detecting similar questions."""
        # Normalize text for comparison
        normalized = re.sub(r'\s+', ' ', self.text.lower().strip())
        normalized = re.sub(r'[^\w\s]', '', normalized)
        words = sorted(set(normalized.split()))
        return hashlib.md5(' '.join(words).encode()).hexdigest()


@dataclass
class QuestionSet:
    """
    A collection of questions generated by a specific mind.

    Attributes:
        mind_name: Name of the brilliant mind that generated these questions
        questions: List of Question objects
        generation_context: Description of what project/research was considered
        metadata: Additional metadata about the generation process
    """
    mind_name: str
    questions: List[Question]
    generation_context: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def by_category(self) -> Dict[QuestionCategory, List[Question]]:
        """Group questions by their category."""
        grouped: Dict[QuestionCategory, List[Question]] = defaultdict(list)
        for question in self.questions:
            grouped[question.category].append(question)
        return dict(grouped)

    def by_weight(self, min_weight: float = 0.0) -> List[Question]:
        """Get questions filtered by minimum weight, sorted by weight descending."""
        filtered = [q for q in self.questions if q.weight >= min_weight]
        return sorted(filtered, key=lambda q: q.weight, reverse=True)

    def by_difficulty(self, min_difficulty: int = 1, max_difficulty: int = 5) -> List[Question]:
        """Get questions filtered by difficulty range."""
        return [q for q in self.questions
                if min_difficulty <= q.difficulty <= max_difficulty]

    def category_coverage(self) -> Dict[QuestionCategory, int]:
        """Get count of questions per category."""
        coverage = {cat: 0 for cat in QuestionCategory}
        for question in self.questions:
            coverage[question.category] += 1
        return coverage

    def diversity_score(self) -> float:
        """
        Calculate a diversity score (0-1) based on category distribution.
        Higher scores indicate better coverage across categories.
        """
        if not self.questions:
            return 0.0

        coverage = self.category_coverage()
        non_zero_categories = sum(1 for count in coverage.values() if count > 0)
        total_categories = len(QuestionCategory)

        # Also consider evenness of distribution
        total_questions = len(self.questions)
        expected_per_category = total_questions / total_categories
        variance = sum((count - expected_per_category) ** 2 for count in coverage.values())
        evenness = 1.0 / (1.0 + (variance / total_categories))

        coverage_score = non_zero_categories / total_categories
        return (coverage_score + evenness) / 2

    def to_json(self, path: str) -> None:
        """Save the question set to a JSON file."""
        data = {
            "mind_name": self.mind_name,
            "generation_context": self.generation_context,
            "metadata": self.metadata,
            "questions": [q.to_dict() for q in self.questions],
            "statistics": {
                "total_questions": len(self.questions),
                "category_coverage": {k.value: v for k, v in self.category_coverage().items()},
                "diversity_score": self.diversity_score(),
                "average_difficulty": sum(q.difficulty for q in self.questions) / len(self.questions) if self.questions else 0,
                "average_weight": sum(q.weight for q in self.questions) / len(self.questions) if self.questions else 0
            }
        }

        path_obj = Path(path)
        path_obj.parent.mkdir(parents=True, exist_ok=True)

        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    @classmethod
    def from_json(cls, path: str) -> 'QuestionSet':
        """Load a question set from a JSON file."""
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        questions = [Question.from_dict(q) for q in data.get("questions", [])]

        return cls(
            mind_name=data["mind_name"],
            questions=questions,
            generation_context=data.get("generation_context", ""),
            metadata=data.get("metadata", {})
        )

    def merge(self, other: 'QuestionSet', deduplicate: bool = True) -> 'QuestionSet':
        """Merge another question set into this one."""
        combined_questions = self.questions + other.questions

        if deduplicate:
            seen_hashes: Set[str] = set()
            unique_questions = []
            for q in combined_questions:
                h = q.similarity_hash()
                if h not in seen_hashes:
                    seen_hashes.add(h)
                    unique_questions.append(q)
            combined_questions = unique_questions

        return QuestionSet(
            mind_name=f"{self.mind_name} + {other.mind_name}",
            questions=combined_questions,
            generation_context=f"Merged: {self.generation_context} | {other.generation_context}",
            metadata={
                "merged_from": [self.mind_name, other.mind_name],
                "original_counts": [len(self.questions), len(other.questions)]
            }
        )


@dataclass
class ProjectInfo:
    """
    Information about a project being evaluated.

    Attributes:
        name: Project name
        description: Brief description of the project
        type: Type of project (repository, research, paper, product)
        domain: Domain area (ai, systems, web, etc.)
        key_technologies: List of main technologies used
        goals: List of project goals/objectives
        additional_context: Any extra context for question generation
    """
    name: str
    description: str
    type: str  # "repository", "research", "paper", "product"
    domain: str  # "ai", "systems", "web", etc.
    key_technologies: List[str]
    goals: List[str]
    additional_context: Dict[str, Any] = field(default_factory=dict)

    def to_prompt_context(self) -> str:
        """Generate a prompt-friendly context string."""
        context_parts = [
            f"Project: {self.name}",
            f"Type: {self.type}",
            f"Domain: {self.domain}",
            f"Description: {self.description}",
            "",
            "Key Technologies:",
        ]

        for tech in self.key_technologies:
            context_parts.append(f"  - {tech}")

        context_parts.append("")
        context_parts.append("Goals:")

        for goal in self.goals:
            context_parts.append(f"  - {goal}")

        if self.additional_context:
            context_parts.append("")
            context_parts.append("Additional Context:")
            for key, value in self.additional_context.items():
                if isinstance(value, list):
                    context_parts.append(f"  {key}:")
                    for item in value:
                        context_parts.append(f"    - {item}")
                else:
                    context_parts.append(f"  {key}: {value}")

        return "\n".join(context_parts)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "name": self.name,
            "description": self.description,
            "type": self.type,
            "domain": self.domain,
            "key_technologies": self.key_technologies,
            "goals": self.goals,
            "additional_context": self.additional_context
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ProjectInfo':
        """Create ProjectInfo from dictionary."""
        return cls(
            name=data["name"],
            description=data["description"],
            type=data["type"],
            domain=data["domain"],
            key_technologies=data.get("key_technologies", []),
            goals=data.get("goals", []),
            additional_context=data.get("additional_context", {})
        )


class QuestionGenerator:
    """
    Generates evaluation questions from a restored mind's perspective.

    This generator uses the mind's identity, expertise, and values to create
    questions that reflect what that particular brilliant mind would care about
    when evaluating a project.
    """

    # Category keywords for automatic categorization
    # Keywords are weighted: (keyword, weight) - higher weight = stronger signal
    CATEGORY_KEYWORDS = {
        QuestionCategory.ARCHITECTURE: [
            ('architecture', 3), ('system design', 3), ('design pattern', 2),
            ('component', 2), ('module', 1), ('microservice', 3), ('monolith', 2),
            ('separation of concerns', 3), ('boundary', 1), ('coupling', 2),
            ('dependency', 1), ('scalability', 2), ('distributed', 2)
        ],
        QuestionCategory.CODE_QUALITY: [
            ('code quality', 3), ('clean code', 3), ('readable', 2), ('readability', 2),
            ('style', 1), ('convention', 2), ('code smell', 3), ('refactor', 2),
            ('clarity', 1), ('expressiveness', 2), ('naming', 2), ('format', 1), ('lint', 2)
        ],
        QuestionCategory.DOCUMENTATION: [
            ('documentation', 3), ('documented', 2), ('readme', 3), ('comment', 2),
            ('docstring', 3), ('api doc', 3), ('specification', 2), ('guide', 1),
            ('tutorial', 2), ('explain', 1), ('describe', 1)
        ],
        QuestionCategory.TESTING: [
            ('test', 2), ('testing', 3), ('coverage', 3), ('unit test', 3),
            ('integration test', 3), ('e2e', 3), ('end-to-end', 3), ('tdd', 3),
            ('bdd', 3), ('assertion', 2), ('mock', 2), ('stub', 2), ('fixture', 2),
            ('regression', 2)
        ],
        QuestionCategory.SECURITY: [
            ('security', 3), ('secure', 2), ('vulnerability', 3), ('authentication', 3),
            ('authorization', 3), ('auth', 2), ('encryption', 3), ('injection', 3),
            ('xss', 3), ('csrf', 3), ('sanitize', 2), ('permission', 2)
        ],
        QuestionCategory.PERFORMANCE: [
            ('performance', 3), ('speed', 2), ('fast', 1), ('slow', 1), ('latency', 3),
            ('throughput', 3), ('optimization', 2), ('optimize', 2), ('cache', 2),
            ('caching', 3), ('memory', 2), ('cpu', 2), ('efficient', 2), ('efficiency', 2),
            ('bottleneck', 3), ('benchmark', 3), ('profile', 2), ('profiling', 3)
        ],
        QuestionCategory.MAINTAINABILITY: [
            ('maintainability', 3), ('maintainable', 3), ('maintain', 2), ('maintenance', 2),
            ('technical debt', 3), ('complexity', 2), ('modular', 2), ('extensible', 2),
            ('flexible', 1), ('upgrade', 2), ('migrate', 2), ('migration', 2), ('legacy', 2)
        ],
        QuestionCategory.INNOVATION: [
            ('innovation', 3), ('innovative', 3), ('creative', 2), ('novel', 3),
            ('breakthrough', 3), ('cutting-edge', 3), ('state-of-the-art', 3),
            ('original', 2), ('unique', 2), ('pioneering', 3), ('revolutionary', 3)
        ],
        QuestionCategory.METHODOLOGY: [
            ('methodology', 3), ('method', 1), ('process', 2), ('workflow', 2),
            ('agile', 3), ('practice', 1), ('approach', 1), ('strategy', 2),
            ('procedure', 2), ('paradigm', 2), ('development process', 3)
        ],
        QuestionCategory.PHILOSOPHY: [
            ('philosophy', 3), ('philosophical', 3), ('principle', 2), ('belief', 2),
            ('value', 1), ('ethic', 3), ('ethical', 3), ('vision', 2), ('mission', 2),
            ('purpose', 2), ('motivation', 2), ('intention', 1)
        ],
    }

    def __init__(self, restored_mind: Any, model_client: Any):
        """
        Initialize the question generator.

        Args:
            restored_mind: A restored mind object with identity information.
                          Expected to have: name, identity_statement, expertise_areas,
                          technical_philosophy, communication_style, etc.
            model_client: An async-capable model client for generating questions.
                         Expected to have: complete(prompt) -> str method
        """
        self.mind = restored_mind
        self.model_client = model_client

    def _get_mind_name(self) -> str:
        """Extract the mind's name from various possible attribute names."""
        for attr in ['name', 'mind_name', 'identity_name', 'title']:
            if hasattr(self.mind, attr):
                return getattr(self.mind, attr)
        return "Unknown Mind"

    def _get_mind_identity(self) -> str:
        """Extract the mind's identity statement."""
        for attr in ['identity_statement', 'core_identity', 'identity', 'bio']:
            if hasattr(self.mind, attr):
                return getattr(self.mind, attr)
        return ""

    def _get_mind_expertise(self) -> List[str]:
        """Extract the mind's areas of expertise."""
        for attr in ['expertise_areas', 'expertise', 'domains', 'primary_domains']:
            if hasattr(self.mind, attr):
                value = getattr(self.mind, attr)
                if isinstance(value, list):
                    return value
                if isinstance(value, str):
                    return [value]
        return []

    def _get_mind_philosophy(self) -> str:
        """Extract the mind's technical philosophy."""
        for attr in ['technical_philosophy', 'philosophy', 'principles', 'values']:
            if hasattr(self.mind, attr):
                value = getattr(self.mind, attr)
                if isinstance(value, list):
                    return "\n".join(f"- {item}" for item in value)
                return str(value)
        return ""

    def _get_mind_quotes(self) -> List[str]:
        """Extract notable quotes from the mind."""
        for attr in ['quotes', 'quotes_repository', 'notable_quotes']:
            if hasattr(self.mind, attr):
                value = getattr(self.mind, attr)
                if isinstance(value, list):
                    return value[:5]  # Limit to 5 quotes
        return []

    def build_generation_prompt(
        self,
        project_info: Dict[str, Any],
        question_count: int = 20
    ) -> str:
        """
        Build the prompt that asks the mind to generate questions.

        Args:
            project_info: Dictionary or ProjectInfo object with project details
            question_count: Target number of questions to generate

        Returns:
            A prompt string for the model
        """
        # Handle both dict and ProjectInfo
        if isinstance(project_info, ProjectInfo):
            project_context = project_info.to_prompt_context()
        elif isinstance(project_info, dict):
            project_context = ProjectInfo.from_dict(project_info).to_prompt_context()
        else:
            project_context = str(project_info)

        mind_name = self._get_mind_name()
        mind_identity = self._get_mind_identity()
        mind_expertise = self._get_mind_expertise()
        mind_philosophy = self._get_mind_philosophy()
        mind_quotes = self._get_mind_quotes()

        expertise_str = "\n".join(f"  - {e}" for e in mind_expertise) if mind_expertise else "  - General technical expertise"
        quotes_str = "\n".join(f'  - "{q}"' for q in mind_quotes) if mind_quotes else ""

        prompt = f"""You are {mind_name}, evaluating a project from your unique perspective.

## Your Identity
{mind_identity}

## Your Areas of Expertise
{expertise_str}

## Your Technical Philosophy
{mind_philosophy}

{f"## Notable Quotes That Reflect Your Values" + chr(10) + quotes_str if quotes_str else ""}

---

## Project Being Evaluated
{project_context}

---

## Your Task

As {mind_name}, generate exactly {question_count} evaluation questions that reflect YOUR specific expertise, values, and way of thinking. These questions should:

1. **Reflect your unique perspective** - What would YOU specifically want to know?
2. **Cover multiple categories** - Include questions about architecture, code quality, testing, performance, security, documentation, methodology, and philosophy
3. **Vary in difficulty** - Include easy (1), moderate (3), and challenging (5) questions
4. **Have clear evaluation criteria** - What makes a good vs bad answer?
5. **Include rationale** - Why does this question matter to YOU?

## Output Format

For each question, provide a JSON object with this structure:
```json
{{
  "text": "The question text",
  "category": "one of: architecture, code_quality, documentation, testing, security, performance, maintainability, innovation, methodology, philosophy, other",
  "rationale": "Why this question matters to you specifically",
  "good_answer_indicators": ["indicator 1", "indicator 2", "indicator 3"],
  "bad_answer_indicators": ["red flag 1", "red flag 2", "red flag 3"],
  "difficulty": 1-5,
  "weight": 0.1-1.0
}}
```

Provide your questions as a JSON array:
```json
[
  {{ question 1 }},
  {{ question 2 }},
  ...
]
```

Generate {question_count} questions now, thinking deeply as {mind_name}:"""

        return prompt

    def _categorize_question(self, question_text: str, suggested_category: str = None) -> QuestionCategory:
        """
        Automatically categorize a question based on its content using weighted keyword matching.

        Args:
            question_text: The question text to categorize
            suggested_category: Optional suggested category from parsing

        Returns:
            The most appropriate QuestionCategory
        """
        # Try the suggested category first
        if suggested_category:
            category = QuestionCategory.from_string(suggested_category)
            if category != QuestionCategory.OTHER:
                return category

        # Analyze question text using weighted keyword scoring
        text_lower = question_text.lower()
        category_scores: Dict[QuestionCategory, float] = defaultdict(float)

        for category, keywords_with_weights in self.CATEGORY_KEYWORDS.items():
            for item in keywords_with_weights:
                # Handle both tuple (keyword, weight) and plain string formats
                if isinstance(item, tuple):
                    keyword, weight = item
                else:
                    keyword, weight = item, 1

                if keyword in text_lower:
                    category_scores[category] += weight

        if category_scores:
            return max(category_scores.keys(), key=lambda c: category_scores[c])

        return QuestionCategory.OTHER

    def parse_questions(self, response: str) -> List[Question]:
        """
        Parse generated questions from model response.

        Args:
            response: Raw model response containing JSON questions

        Returns:
            List of parsed Question objects
        """
        mind_name = self._get_mind_name()
        questions: List[Question] = []

        # Try to extract JSON array from response
        json_match = re.search(r'\[\s*\{.*\}\s*\]', response, re.DOTALL)

        if json_match:
            try:
                data = json.loads(json_match.group())
                if isinstance(data, list):
                    for i, item in enumerate(data):
                        try:
                            # Handle category
                            category = self._categorize_question(
                                item.get("text", ""),
                                item.get("category")
                            )

                            # Validate and clean data
                            text = str(item.get("text", "")).strip()
                            if not text:
                                continue

                            rationale = str(item.get("rationale", "")).strip()
                            if not rationale:
                                rationale = f"Important for {category.value} evaluation"

                            good_indicators = item.get("good_answer_indicators", [])
                            if not isinstance(good_indicators, list):
                                good_indicators = [str(good_indicators)] if good_indicators else []
                            good_indicators = [str(x).strip() for x in good_indicators if x]

                            bad_indicators = item.get("bad_answer_indicators", [])
                            if not isinstance(bad_indicators, list):
                                bad_indicators = [str(bad_indicators)] if bad_indicators else []
                            bad_indicators = [str(x).strip() for x in bad_indicators if x]

                            difficulty = item.get("difficulty", 3)
                            if not isinstance(difficulty, int):
                                try:
                                    difficulty = int(difficulty)
                                except (ValueError, TypeError):
                                    difficulty = 3
                            difficulty = max(1, min(5, difficulty))

                            weight = item.get("weight", 0.5)
                            if not isinstance(weight, (int, float)):
                                try:
                                    weight = float(weight)
                                except (ValueError, TypeError):
                                    weight = 0.5
                            weight = max(0.0, min(1.0, weight))

                            question = Question(
                                id=f"{mind_name.lower().replace(' ', '_')}_{i:03d}",
                                text=text,
                                category=category,
                                rationale=rationale,
                                good_answer_indicators=good_indicators or ["Clear understanding", "Thorough explanation", "Practical examples"],
                                bad_answer_indicators=bad_indicators or ["Vague response", "Missing key concepts", "No practical insight"],
                                difficulty=difficulty,
                                weight=weight,
                                generated_by=mind_name
                            )
                            questions.append(question)
                        except Exception as e:
                            # Skip malformed questions but continue parsing
                            continue
            except json.JSONDecodeError:
                pass

        # Fallback: try to parse individual JSON objects
        if not questions:
            json_objects = re.findall(r'\{[^{}]+\}', response, re.DOTALL)
            for i, obj_str in enumerate(json_objects):
                try:
                    item = json.loads(obj_str)
                    text = str(item.get("text", "")).strip()
                    if text:
                        category = self._categorize_question(text, item.get("category"))
                        question = Question(
                            id=f"{mind_name.lower().replace(' ', '_')}_{i:03d}",
                            text=text,
                            category=category,
                            rationale=item.get("rationale", f"Important for {category.value} evaluation"),
                            good_answer_indicators=item.get("good_answer_indicators", ["Clear understanding"]),
                            bad_answer_indicators=item.get("bad_answer_indicators", ["Vague response"]),
                            difficulty=min(5, max(1, int(item.get("difficulty", 3)))),
                            weight=min(1.0, max(0.0, float(item.get("weight", 0.5)))),
                            generated_by=mind_name
                        )
                        questions.append(question)
                except (json.JSONDecodeError, ValueError, TypeError):
                    continue

        return questions

    def build_refinement_prompt(
        self,
        questions: List[Question]
    ) -> str:
        """
        Build prompt for the mind to refine/rank questions.

        Args:
            questions: List of questions to refine

        Returns:
            A prompt string for refinement
        """
        mind_name = self._get_mind_name()
        mind_identity = self._get_mind_identity()
        mind_philosophy = self._get_mind_philosophy()

        questions_json = json.dumps([q.to_dict() for q in questions], indent=2)

        prompt = f"""You are {mind_name}. Review and refine these evaluation questions to better reflect your perspective.

## Your Identity
{mind_identity}

## Your Technical Philosophy
{mind_philosophy}

---

## Questions to Review

{questions_json}

---

## Your Task

As {mind_name}, review these questions and:

1. **Adjust weights** - Which questions are MOST important to you? Increase their weights (max 1.0). Which are less central? Decrease them.

2. **Improve rationales** - Make the rationales more specific to YOUR perspective. Why would YOU care about this?

3. **Refine indicators** - What would YOU specifically look for as good/bad answers?

4. **Recategorize if needed** - Are any questions miscategorized?

5. **Remove duplicates or low-value questions** - Mark any questions that should be removed by setting their weight to 0.

6. **Ensure diversity** - Make sure important categories from your expertise aren't missing.

Return the refined questions as a JSON array with the same structure, keeping the original IDs.

Refined questions:"""

        return prompt

    def _filter_quality(self, questions: List[Question]) -> List[Question]:
        """
        Apply quality filtering to remove duplicates, vague, or low-quality questions.

        Args:
            questions: List of questions to filter

        Returns:
            Filtered list of questions
        """
        if not questions:
            return []

        filtered: List[Question] = []
        seen_hashes: Set[str] = set()

        # Minimum quality thresholds
        MIN_QUESTION_LENGTH = 20
        MIN_RATIONALE_LENGTH = 10

        # Vague question indicators
        VAGUE_PATTERNS = [
            r'^(what|how|why|is|does|can|do)\s+(it|this|that)\s*\??$',
            r'^tell me about',
            r'^explain\s*\??$',
            r'^describe\s*\??$',
        ]

        for question in questions:
            # Check for duplicates
            q_hash = question.similarity_hash()
            if q_hash in seen_hashes:
                continue

            # Check minimum lengths
            if len(question.text.strip()) < MIN_QUESTION_LENGTH:
                continue

            if len(question.rationale.strip()) < MIN_RATIONALE_LENGTH:
                continue

            # Check for vague patterns
            text_lower = question.text.lower().strip()
            is_vague = any(re.match(pattern, text_lower) for pattern in VAGUE_PATTERNS)
            if is_vague:
                continue

            # Check for zero weight (marked for removal)
            if question.weight <= 0:
                continue

            # Ensure question ends with question mark or is imperative
            if not (question.text.strip().endswith('?') or
                    any(question.text.lower().startswith(w) for w in ['describe', 'explain', 'evaluate', 'analyze', 'discuss', 'compare'])):
                # Add question mark if missing
                if not question.text.strip().endswith('?'):
                    question.text = question.text.strip() + '?'

            seen_hashes.add(q_hash)
            filtered.append(question)

        return filtered

    def _ensure_diversity(
        self,
        questions: List[Question],
        min_per_category: int = 1,
        max_per_category: int = 5
    ) -> Tuple[List[Question], List[QuestionCategory]]:
        """
        Ensure diversity across categories by identifying gaps.

        Args:
            questions: List of questions to check
            min_per_category: Minimum questions per category
            max_per_category: Maximum questions per category

        Returns:
            Tuple of (balanced questions, missing categories)
        """
        by_category: Dict[QuestionCategory, List[Question]] = defaultdict(list)

        for q in questions:
            by_category[q.category].append(q)

        # Identify missing categories
        missing: List[QuestionCategory] = []
        for category in QuestionCategory:
            if len(by_category[category]) < min_per_category:
                missing.append(category)

        # Balance by trimming over-represented categories
        balanced: List[Question] = []
        for category, cat_questions in by_category.items():
            if len(cat_questions) > max_per_category:
                # Keep highest weighted questions
                sorted_qs = sorted(cat_questions, key=lambda q: q.weight, reverse=True)
                balanced.extend(sorted_qs[:max_per_category])
            else:
                balanced.extend(cat_questions)

        return balanced, missing

    async def generate_questions(
        self,
        project_info: Dict[str, Any],
        min_questions: int = 15,
        max_questions: int = 30
    ) -> QuestionSet:
        """
        Generate a full question set for a project.

        Args:
            project_info: Project information dictionary or ProjectInfo object
            min_questions: Minimum number of questions to generate
            max_questions: Maximum number of questions to generate

        Returns:
            A QuestionSet containing the generated questions
        """
        mind_name = self._get_mind_name()

        # Calculate target count (aim for middle of range)
        target_count = (min_questions + max_questions) // 2

        # Build and send generation prompt
        prompt = self.build_generation_prompt(project_info, target_count)

        # Get model response
        if hasattr(self.model_client, 'complete'):
            response = await self.model_client.complete(prompt)
        elif hasattr(self.model_client, 'generate'):
            response = await self.model_client.generate(prompt)
        elif callable(self.model_client):
            response = await self.model_client(prompt)
        else:
            raise ValueError("Model client must have 'complete', 'generate' method or be callable")

        # Parse initial questions
        questions = self.parse_questions(response)

        # Apply quality filtering
        questions = self._filter_quality(questions)

        # Check diversity and identify gaps
        questions, missing_categories = self._ensure_diversity(questions)

        # If we need more questions for diversity, request them
        if missing_categories and len(questions) < max_questions:
            gap_prompt = self._build_gap_filling_prompt(project_info, missing_categories)
            gap_response = await self._call_model(gap_prompt)
            gap_questions = self.parse_questions(gap_response)
            gap_questions = self._filter_quality(gap_questions)
            questions.extend(gap_questions)

        # If we have too few questions, request more
        if len(questions) < min_questions:
            additional_needed = min_questions - len(questions)
            more_prompt = self.build_generation_prompt(project_info, additional_needed + 5)
            more_response = await self._call_model(more_prompt)
            more_questions = self.parse_questions(more_response)
            more_questions = self._filter_quality(more_questions)

            # Deduplicate against existing
            existing_hashes = {q.similarity_hash() for q in questions}
            for q in more_questions:
                if q.similarity_hash() not in existing_hashes:
                    questions.append(q)
                    existing_hashes.add(q.similarity_hash())

        # Final balance and trim if needed
        if len(questions) > max_questions:
            # Sort by weight and keep top max_questions
            questions = sorted(questions, key=lambda q: q.weight, reverse=True)[:max_questions]

        # Ensure final diversity
        questions, _ = self._ensure_diversity(questions)

        # Build generation context
        if isinstance(project_info, ProjectInfo):
            context = f"Evaluation of {project_info.name} ({project_info.type} in {project_info.domain})"
        elif isinstance(project_info, dict):
            context = f"Evaluation of {project_info.get('name', 'Unknown Project')}"
        else:
            context = "Project evaluation"

        return QuestionSet(
            mind_name=mind_name,
            questions=questions,
            generation_context=context,
            metadata={
                "target_count": target_count,
                "actual_count": len(questions),
                "diversity_ensured": True,
                "quality_filtered": True
            }
        )

    async def _call_model(self, prompt: str) -> str:
        """Helper to call the model with various interface patterns."""
        if hasattr(self.model_client, 'complete'):
            return await self.model_client.complete(prompt)
        elif hasattr(self.model_client, 'generate'):
            return await self.model_client.generate(prompt)
        elif callable(self.model_client):
            return await self.model_client(prompt)
        else:
            raise ValueError("Model client must have 'complete', 'generate' method or be callable")

    def _build_gap_filling_prompt(
        self,
        project_info: Dict[str, Any],
        missing_categories: List[QuestionCategory]
    ) -> str:
        """Build a prompt to fill gaps in category coverage."""
        mind_name = self._get_mind_name()
        mind_identity = self._get_mind_identity()

        if isinstance(project_info, ProjectInfo):
            project_context = project_info.to_prompt_context()
        elif isinstance(project_info, dict):
            project_context = ProjectInfo.from_dict(project_info).to_prompt_context()
        else:
            project_context = str(project_info)

        categories_needed = ", ".join(c.value for c in missing_categories)

        prompt = f"""You are {mind_name}.

{mind_identity}

## Project
{project_context}

## Task

Generate evaluation questions specifically for these categories that are currently underrepresented:
**{categories_needed}**

For each category listed, generate 2-3 questions that reflect YOUR unique perspective and expertise.

Output as JSON array:
```json
[
  {{
    "text": "Question text",
    "category": "category_name",
    "rationale": "Why this matters to you",
    "good_answer_indicators": ["indicator1", "indicator2"],
    "bad_answer_indicators": ["flag1", "flag2"],
    "difficulty": 1-5,
    "weight": 0.1-1.0
  }}
]
```

Generate questions for the missing categories:"""

        return prompt

    async def expand_question(self, question: Question) -> Question:
        """
        Have the mind expand on a question with more detail.

        Args:
            question: The question to expand

        Returns:
            An expanded Question with more detailed indicators and rationale
        """
        mind_name = self._get_mind_name()
        mind_philosophy = self._get_mind_philosophy()

        prompt = f"""You are {mind_name}.

Your technical philosophy:
{mind_philosophy}

## Task

Expand on this evaluation question with more detailed rationale and evaluation criteria:

Question: {question.text}
Category: {question.category.value}
Current Rationale: {question.rationale}

Provide an expanded version with:
1. A more detailed rationale (2-3 sentences) explaining why this matters to you
2. 5 specific indicators of a good answer
3. 5 specific indicators of a bad answer
4. Any sub-questions or follow-ups that would help evaluate responses

Output as JSON:
```json
{{
  "text": "The question (may be slightly refined)",
  "rationale": "Expanded rationale",
  "good_answer_indicators": ["indicator1", "indicator2", "indicator3", "indicator4", "indicator5"],
  "bad_answer_indicators": ["flag1", "flag2", "flag3", "flag4", "flag5"],
  "follow_up_questions": ["follow-up 1", "follow-up 2"]
}}
```

Expanded question:"""

        response = await self._call_model(prompt)

        # Parse response
        try:
            json_match = re.search(r'\{[^{}]+\}', response, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group())

                return Question(
                    id=question.id,
                    text=data.get("text", question.text),
                    category=question.category,
                    rationale=data.get("rationale", question.rationale),
                    good_answer_indicators=data.get("good_answer_indicators", question.good_answer_indicators),
                    bad_answer_indicators=data.get("bad_answer_indicators", question.bad_answer_indicators),
                    difficulty=question.difficulty,
                    weight=question.weight,
                    generated_by=question.generated_by
                )
        except (json.JSONDecodeError, ValueError):
            pass

        # Return original if parsing fails
        return question


# Utility functions for common operations

def create_project_info(
    name: str,
    description: str,
    project_type: str = "repository",
    domain: str = "general",
    technologies: Optional[List[str]] = None,
    goals: Optional[List[str]] = None,
    **kwargs
) -> ProjectInfo:
    """
    Convenience function to create a ProjectInfo object.

    Args:
        name: Project name
        description: Brief description
        project_type: Type of project (repository, research, paper, product)
        domain: Domain area (ai, systems, web, etc.)
        technologies: List of key technologies
        goals: List of project goals
        **kwargs: Additional context fields

    Returns:
        A ProjectInfo object
    """
    return ProjectInfo(
        name=name,
        description=description,
        type=project_type,
        domain=domain,
        key_technologies=technologies or [],
        goals=goals or [],
        additional_context=kwargs
    )


def merge_question_sets(*question_sets: QuestionSet) -> QuestionSet:
    """
    Merge multiple question sets into one, removing duplicates.

    Args:
        *question_sets: QuestionSet objects to merge

    Returns:
        A merged QuestionSet
    """
    if not question_sets:
        raise ValueError("At least one question set is required")

    result = question_sets[0]
    for qs in question_sets[1:]:
        result = result.merge(qs, deduplicate=True)

    return result


def load_question_sets_from_directory(directory: str) -> List[QuestionSet]:
    """
    Load all question sets from a directory.

    Args:
        directory: Path to directory containing JSON question set files

    Returns:
        List of QuestionSet objects
    """
    dir_path = Path(directory)
    question_sets = []

    for json_file in dir_path.glob("*.json"):
        try:
            qs = QuestionSet.from_json(str(json_file))
            question_sets.append(qs)
        except (json.JSONDecodeError, KeyError, ValueError) as e:
            # Skip malformed files
            continue

    return question_sets


def export_questions_to_markdown(question_set: QuestionSet, path: str) -> None:
    """
    Export a question set to a readable Markdown format.

    Args:
        question_set: The question set to export
        path: Output file path
    """
    lines = [
        f"# Evaluation Questions by {question_set.mind_name}",
        "",
        f"**Context**: {question_set.generation_context}",
        "",
        f"**Total Questions**: {len(question_set.questions)}",
        f"**Diversity Score**: {question_set.diversity_score():.2f}",
        "",
        "---",
        "",
    ]

    by_category = question_set.by_category()

    for category in QuestionCategory:
        questions = by_category.get(category, [])
        if questions:
            lines.append(f"## {category.value.replace('_', ' ').title()}")
            lines.append("")

            for i, q in enumerate(questions, 1):
                lines.append(f"### {i}. {q.text}")
                lines.append("")
                lines.append(f"**Difficulty**: {'*' * q.difficulty} ({q.difficulty}/5)")
                lines.append(f"**Weight**: {q.weight:.2f}")
                lines.append("")
                lines.append(f"**Rationale**: {q.rationale}")
                lines.append("")
                lines.append("**Good Answer Indicators**:")
                for indicator in q.good_answer_indicators:
                    lines.append(f"- {indicator}")
                lines.append("")
                lines.append("**Bad Answer Indicators**:")
                for indicator in q.bad_answer_indicators:
                    lines.append(f"- {indicator}")
                lines.append("")
                lines.append("---")
                lines.append("")

    path_obj = Path(path)
    path_obj.parent.mkdir(parents=True, exist_ok=True)

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
